# Generated by Django 5.0.8 on 2025-06-23 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("attachee", "Attachee"),
                            ("visitor", "Visitor"),
                            ("member", "Member"),
                            ("staff", "Staff"),
                            ("not_sure", "Not Sure"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("communication", "Communication"),
                            ("creatives", "Creatives"),
                            ("tech", "Tech Department"),
                            ("youth_engagement", "Youth Engagement"),
                            ("heritage", "Heritage"),
                            ("admin", "Admin"),
                            ("finance", "Finance"),
                            ("entrepreneurship", "Entrepreneurship"),
                        ],
                        max_length=30,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                        ],
                        default="checked_in",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-date", "user"],
            },
        ),
    ]
